package net.projecteuler.java;

/**
 * Pentagonal numbers are generated by the formula, P<sub>n</sub>=n(3n-1)/2.
 * The first ten pentagonal numbers are:</br>
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...</br>
 * It can be seen that P<sub>4</sub> + P<sub>7</sub> = 22 + 70 = 92 = P<sub>8</sub>.
 * However, their difference, 70 - 22 = 48, is not pentagonal.</br>
 * Find the pair of pentagonal numbers, P<sub>j</sub> and P<sub>k</sub>,
 * for which their sum and difference is pentagonal and D = |P<sub>k</sub> - P<sub>j</sub>| is minimised;
 * what is the value of D?
 *
 * @author vuser
 *
 */
public class Problem044 {

	public static void main(String[] args) {
		assert calculate() == 5482660 : "failed";
	}

	private static int calculate() {
		int diff = 0;
		search: for (int j = 1; ; j++) {
			int pj = (3 * j * j - j) / 2;
			for (int k = j - 1 ; k > 0; k--) {
				int pk = (3 * k * k - k) / 2;
				// Test of pentagonal number
				double ndiff = (Math.sqrt(24 * (pj - pk) + 1) + 1) / 6;
				if (ndiff == Math.floor(ndiff)) { // If diff is integer checks the sum too
					double nsum = (Math.sqrt(24 * (pj + pk) + 1) + 1) / 6;
					if (nsum == Math.floor(nsum)) {
						diff = pj - pk;
						break search;
					}
				}
			}
		}
		return diff;
	}
}