package net.projecteuler.java;

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Consider all integer combinations of ab for 2 <= a <= 5 and 2 <= b <= 5:</br>
 * 2<sup>2</sup>=4, 2<sup>3</sup>=8, 2<sup>4</sup>=16, 2<sup>5</sup>=32</br>
 * 3<sup>2</sup>=9, 3<sup>3</sup>=27, 3<sup>4</sup>=81, 3<sup>5</sup>=243</br>
 * 4<sup>2</sup>=16, 4<sup>3</sup>=64, 4<sup>4</sup>=256, 4<sup>5</sup>=1024</br>
 * 5<sup>2</sup>=25, 5<sup>3</sup>=125, 5<sup>4</sup>=625, 5<sup>5</sup>=3125</br>
 * If they are then placed in numerical order, with any repeats removed,
 * we get the following sequence of 15 distinct terms:</br>
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125</br>
 * How many distinct terms are in the sequence generated by ab for 2  a  100 and 2  b  100?
 *
 * @author vuser
 *
 */
public class Problem029 {

	public static void main(String[] args) {
		assert calculate() == 9183 : "failed";
	}

	private static int calculate() {
		int min = 2;
		int max = 100;

		Set<BigInteger> values = new HashSet<BigInteger>();
		for (int a = min; a <= max; a++) {
			BigInteger i = new BigInteger(String.valueOf(a));
			for (int b = min; b <= max; b++) {
				values.add(i.pow(b));
			}
		}
		return values.size();
	}
}
