package net.projecteuler.java;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * @author vuser
 * 
 */
public class Problem002 {

	private static long calculate(long a, long b, long sum) {
		if (a < 4000000) {
			if (a % 2 == 0) {
				sum += a;
			}
			return calculate(b, a + b, sum);
		}
		return sum;
	}

	public static void main(String[] args) {
		assert calculate(1, 2, 0) == 4613732 : "failed";
	}
}
