package net.projecteuler.java;

/**
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:</br>
 * Triangle:     Tn=n(n + 1)/2   1, 3, 6, 10, 15, ...</br>
 * Pentagonal:   Pn=n(3n - 1)/2  1, 5, 12, 22, 35, ...</br>
 * Hexagonal:    Hn=n(2n - 1)    1, 6, 15, 28, 45, ...</br>
 * It can be verified that T<sub>285</sub> = P<sub>165</sub> = H<sub>143</sub> = 40755.</br>
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 * @author vuser
 *
 */
public class Problem045 {

	public static void main(String[] args) {
		assert calculate() == 1533776805L : "failed";
	}

	/**
	 * Every hexagonal number is a triangular number, so only hexagonal number should be
	 * calculated and checked as pentgagonal.
	 * @return
	 */
	private static long calculate() {
		long triangle = 0;
		search: for (int i = 166; ; i++) { // We know that T285 = P165 = H143 
			long h = i * (2 * i - 1);
			double pn = (Math.sqrt(24 * h + 1) + 1) / 6;
			if (pn == Math.floor(pn)) {
				triangle = h;
				break search;
			}
		}
		return triangle;
	}
}